"""add_price_snapshots

Revision ID: bfd68f2d8145
Revises: 00656f685102
Create Date: 2026-08-10 05:30:05.665500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd68f2d8145'
down_revision = '00656f685102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('gst_number', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wallet_used', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coupon_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_booking_invoices_booking_reference'), 'booking_invoices', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_booking_invoices_id'), 'booking_invoices', ['id'], unique=False)
    op.create_table('booking_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('ticket_number', sa.String(length=100), nullable=False),
    sa.Column('pnr', sa.String(length=20), nullable=True),
    sa.Column('qr_code_data', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('passenger_details', sa.JSON(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index(op.f('ix_booking_tickets_booking_reference'), 'booking_tickets', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_booking_tickets_id'), 'booking_tickets', ['id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_id'), 'price_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_item_id'), 'price_snapshots', ['item_id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_item_type'), 'price_snapshots', ['item_type'], unique=False)
    op.create_table('special_fare_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fare_type', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('minimum_age', sa.Integer(), nullable=True),
    sa.Column('maximum_age', sa.Integer(), nullable=True),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_fare_configs_fare_type'), 'special_fare_configs', ['fare_type'], unique=True)
    op.create_index(op.f('ix_special_fare_configs_id'), 'special_fare_configs', ['id'], unique=False)
    op.create_table('beta_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beta_feedback_id'), 'beta_feedback', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_id'), 'emergency_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=True)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_alerts', sa.Boolean(), nullable=False),
    sa.Column('sms_alerts', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_alerts', sa.Boolean(), nullable=False),
    sa.Column('push_alerts', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('travel_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_airline', sa.String(length=100), nullable=True),
    sa.Column('preferred_hotel_chain', sa.String(length=100), nullable=True),
    sa.Column('preferred_cabin_class', sa.String(length=100), nullable=True),
    sa.Column('meal_preference', sa.String(length=100), nullable=True),
    sa.Column('seat_preference', sa.String(length=100), nullable=True),
    sa.Column('travel_style', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_preferences_id'), 'travel_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_travel_preferences_user_id'), 'travel_preferences', ['user_id'], unique=True)
    op.create_table('travellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('passport', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('meal', sa.String(length=100), nullable=True),
    sa.Column('seat', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travellers_id'), 'travellers', ['id'], unique=False)
    op.create_index(op.f('ix_travellers_user_id'), 'travellers', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('mobile_number', sa.String(length=50), nullable=True),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('passport_number', sa.String(length=100), nullable=True),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('pan_card', sa.String(length=100), nullable=True),
    sa.Column('aadhaar', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_activity_bookings_tenant_id'), 'activity_bookings', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('affiliate_referrals_booking_ref_key'), 'affiliate_referrals', type_='unique')
    op.create_index(op.f('ix_affiliate_referrals_booking_ref'), 'affiliate_referrals', ['booking_ref'], unique=True)
    op.create_index(op.f('ix_affiliate_referrals_id'), 'affiliate_referrals', ['id'], unique=False)
    op.create_index(op.f('ix_agencies_id'), 'agencies', ['id'], unique=False)
    op.create_index(op.f('ix_agents_staff_id'), 'agents_staff', ['id'], unique=False)
    op.drop_constraint(op.f('api_keys_hashed_key_key'), 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_approval_workflows_corporate_id'), 'approval_workflows', ['corporate_id'], unique=False)
    op.create_index(op.f('ix_approval_workflows_id'), 'approval_workflows', ['id'], unique=False)
    op.create_index(op.f('ix_approval_workflows_manager_user_id'), 'approval_workflows', ['manager_user_id'], unique=False)
    op.create_index(op.f('ix_bus_bookings_tenant_id'), 'bus_bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cab_bookings_tenant_id'), 'cab_bookings', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('commission_records_booking_ref_key'), 'commission_records', type_='unique')
    op.create_index(op.f('ix_commission_records_booking_ref'), 'commission_records', ['booking_ref'], unique=True)
    op.create_index(op.f('ix_commission_records_id'), 'commission_records', ['id'], unique=False)
    op.create_index(op.f('ix_corporate_accounts_id'), 'corporate_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_corporate_accounts_tenant_id'), 'corporate_accounts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_corporate_wallet_transactions_id'), 'corporate_wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_corporate_wallet_transactions_wallet_id'), 'corporate_wallet_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_corporate_wallets_corporate_id'), 'corporate_wallets', ['corporate_id'], unique=False)
    op.create_index(op.f('ix_corporate_wallets_id'), 'corporate_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_cost_centers_code'), 'cost_centers', ['code'], unique=False)
    op.create_index(op.f('ix_cost_centers_corporate_id'), 'cost_centers', ['corporate_id'], unique=False)
    op.create_index(op.f('ix_cost_centers_id'), 'cost_centers', ['id'], unique=False)
    op.create_index(op.f('ix_cruise_bookings_tenant_id'), 'cruise_bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_customer_assignments_id'), 'customer_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_corporate_id'), 'departments', ['corporate_id'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_developer_profiles_id'), 'developer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_developer_profiles_tenant_id'), 'developer_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_developer_profiles_user_id'), 'developer_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_department_id'), 'employee_profiles', ['department_id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_id'), 'employee_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_manager_id'), 'employee_profiles', ['manager_id'], unique=False)
    op.create_index(op.f('ix_flight_bookings_tenant_id'), 'flight_bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_forex_orders_tenant_id'), 'forex_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_holiday_package_bookings_tenant_id'), 'holiday_package_bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_hotel_bookings_tenant_id'), 'hotel_bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_insurance_policies_tenant_id'), 'insurance_policies', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_marketplace_partners_id'), 'marketplace_partners', ['id'], unique=False)
    op.drop_constraint(op.f('oauth_clients_client_id_key'), 'oauth_clients', type_='unique')
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_oauth_clients_id'), 'oauth_clients', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_clients_tenant_id'), 'oauth_clients', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_partner_services_id'), 'partner_services', ['id'], unique=False)
    op.create_index(op.f('ix_saas_invoices_id'), 'saas_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_saas_invoices_tenant_id'), 'saas_invoices', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_saas_subscriptions_id'), 'saas_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_saas_subscriptions_tenant_id'), 'saas_subscriptions', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('tenant_branding_tenant_id_key'), 'tenant_branding', type_='unique')
    op.create_index(op.f('ix_tenant_branding_id'), 'tenant_branding', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_branding_tenant_id'), 'tenant_branding', ['tenant_id'], unique=True)
    op.drop_constraint(op.f('tenant_settings_tenant_id_key'), 'tenant_settings', type_='unique')
    op.create_index(op.f('ix_tenant_settings_id'), 'tenant_settings', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_settings_tenant_id'), 'tenant_settings', ['tenant_id'], unique=True)
    op.drop_constraint(op.f('tenants_custom_domain_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('tenants_subdomain_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_custom_domain'), 'tenants', ['custom_domain'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_subdomain'), 'tenants', ['subdomain'], unique=True)
    op.create_index(op.f('ix_train_bookings_tenant_id'), 'train_bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_travel_policies_corporate_id'), 'travel_policies', ['corporate_id'], unique=False)
    op.create_index(op.f('ix_travel_policies_id'), 'travel_policies', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_vehicle_rental_bookings_tenant_id'), 'vehicle_rental_bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_villa_bookings_tenant_id'), 'villa_bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_visa_applications_tenant_id'), 'visa_applications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_logs_event_type'), 'webhook_delivery_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_logs_id'), 'webhook_delivery_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_logs_subscription_id'), 'webhook_delivery_logs', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_id'), 'webhook_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_tenant_id'), 'webhook_subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_logs_id'), 'workflow_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_rules_id'), 'workflow_rules', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_rules_trigger_event'), 'workflow_rules', ['trigger_event'], unique=False)
    op.create_index(op.f('ix_workflow_steps_id'), 'workflow_steps', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_tenant_id'), 'workspaces', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_tenant_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workflow_steps_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_rules_trigger_event'), table_name='workflow_rules')
    op.drop_index(op.f('ix_workflow_rules_id'), table_name='workflow_rules')
    op.drop_index(op.f('ix_workflow_execution_logs_id'), table_name='workflow_execution_logs')
    op.drop_index(op.f('ix_webhook_subscriptions_tenant_id'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_id'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_delivery_logs_subscription_id'), table_name='webhook_delivery_logs')
    op.drop_index(op.f('ix_webhook_delivery_logs_id'), table_name='webhook_delivery_logs')
    op.drop_index(op.f('ix_webhook_delivery_logs_event_type'), table_name='webhook_delivery_logs')
    op.drop_index(op.f('ix_visa_applications_tenant_id'), table_name='visa_applications')
    op.drop_index(op.f('ix_villa_bookings_tenant_id'), table_name='villa_bookings')
    op.drop_index(op.f('ix_vehicle_rental_bookings_tenant_id'), table_name='vehicle_rental_bookings')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_travel_policies_id'), table_name='travel_policies')
    op.drop_index(op.f('ix_travel_policies_corporate_id'), table_name='travel_policies')
    op.drop_index(op.f('ix_train_bookings_tenant_id'), table_name='train_bookings')
    op.drop_index(op.f('ix_tenants_subdomain'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_custom_domain'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_subdomain_key'), 'tenants', ['subdomain'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_custom_domain_key'), 'tenants', ['custom_domain'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tenant_settings_tenant_id'), table_name='tenant_settings')
    op.drop_index(op.f('ix_tenant_settings_id'), table_name='tenant_settings')
    op.create_unique_constraint(op.f('tenant_settings_tenant_id_key'), 'tenant_settings', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tenant_branding_tenant_id'), table_name='tenant_branding')
    op.drop_index(op.f('ix_tenant_branding_id'), table_name='tenant_branding')
    op.create_unique_constraint(op.f('tenant_branding_tenant_id_key'), 'tenant_branding', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_saas_subscriptions_tenant_id'), table_name='saas_subscriptions')
    op.drop_index(op.f('ix_saas_subscriptions_id'), table_name='saas_subscriptions')
    op.drop_index(op.f('ix_saas_invoices_tenant_id'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_id'), table_name='saas_invoices')
    op.drop_index(op.f('ix_partner_services_id'), table_name='partner_services')
    op.drop_index(op.f('ix_oauth_clients_tenant_id'), table_name='oauth_clients')
    op.drop_index(op.f('ix_oauth_clients_id'), table_name='oauth_clients')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.create_unique_constraint(op.f('oauth_clients_client_id_key'), 'oauth_clients', ['client_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_marketplace_partners_id'), table_name='marketplace_partners')
    op.drop_index(op.f('ix_insurance_policies_tenant_id'), table_name='insurance_policies')
    op.drop_index(op.f('ix_hotel_bookings_tenant_id'), table_name='hotel_bookings')
    op.drop_index(op.f('ix_holiday_package_bookings_tenant_id'), table_name='holiday_package_bookings')
    op.drop_index(op.f('ix_forex_orders_tenant_id'), table_name='forex_orders')
    op.drop_index(op.f('ix_flight_bookings_tenant_id'), table_name='flight_bookings')
    op.drop_index(op.f('ix_employee_profiles_manager_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_department_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_developer_profiles_user_id'), table_name='developer_profiles')
    op.drop_index(op.f('ix_developer_profiles_tenant_id'), table_name='developer_profiles')
    op.drop_index(op.f('ix_developer_profiles_id'), table_name='developer_profiles')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_corporate_id'), table_name='departments')
    op.drop_index(op.f('ix_customer_assignments_id'), table_name='customer_assignments')
    op.drop_index(op.f('ix_cruise_bookings_tenant_id'), table_name='cruise_bookings')
    op.drop_index(op.f('ix_cost_centers_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_corporate_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_code'), table_name='cost_centers')
    op.drop_index(op.f('ix_corporate_wallets_id'), table_name='corporate_wallets')
    op.drop_index(op.f('ix_corporate_wallets_corporate_id'), table_name='corporate_wallets')
    op.drop_index(op.f('ix_corporate_wallet_transactions_wallet_id'), table_name='corporate_wallet_transactions')
    op.drop_index(op.f('ix_corporate_wallet_transactions_id'), table_name='corporate_wallet_transactions')
    op.drop_index(op.f('ix_corporate_accounts_tenant_id'), table_name='corporate_accounts')
    op.drop_index(op.f('ix_corporate_accounts_id'), table_name='corporate_accounts')
    op.drop_index(op.f('ix_commission_records_id'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_booking_ref'), table_name='commission_records')
    op.create_unique_constraint(op.f('commission_records_booking_ref_key'), 'commission_records', ['booking_ref'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cab_bookings_tenant_id'), table_name='cab_bookings')
    op.drop_index(op.f('ix_bus_bookings_tenant_id'), table_name='bus_bookings')
    op.drop_index(op.f('ix_approval_workflows_manager_user_id'), table_name='approval_workflows')
    op.drop_index(op.f('ix_approval_workflows_id'), table_name='approval_workflows')
    op.drop_index(op.f('ix_approval_workflows_corporate_id'), table_name='approval_workflows')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.create_unique_constraint(op.f('api_keys_hashed_key_key'), 'api_keys', ['hashed_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_agents_staff_id'), table_name='agents_staff')
    op.drop_index(op.f('ix_agencies_id'), table_name='agencies')
    op.drop_index(op.f('ix_affiliate_referrals_id'), table_name='affiliate_referrals')
    op.drop_index(op.f('ix_affiliate_referrals_booking_ref'), table_name='affiliate_referrals')
    op.create_unique_constraint(op.f('affiliate_referrals_booking_ref_key'), 'affiliate_referrals', ['booking_ref'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_activity_bookings_tenant_id'), table_name='activity_bookings')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_travellers_user_id'), table_name='travellers')
    op.drop_index(op.f('ix_travellers_id'), table_name='travellers')
    op.drop_table('travellers')
    op.drop_index(op.f('ix_travel_preferences_user_id'), table_name='travel_preferences')
    op.drop_index(op.f('ix_travel_preferences_id'), table_name='travel_preferences')
    op.drop_table('travel_preferences')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_beta_feedback_id'), table_name='beta_feedback')
    op.drop_table('beta_feedback')
    op.drop_index(op.f('ix_special_fare_configs_id'), table_name='special_fare_configs')
    op.drop_index(op.f('ix_special_fare_configs_fare_type'), table_name='special_fare_configs')
    op.drop_table('special_fare_configs')
    op.drop_index(op.f('ix_price_snapshots_item_type'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_item_id'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_booking_tickets_id'), table_name='booking_tickets')
    op.drop_index(op.f('ix_booking_tickets_booking_reference'), table_name='booking_tickets')
    op.drop_table('booking_tickets')
    op.drop_index(op.f('ix_booking_invoices_id'), table_name='booking_invoices')
    op.drop_index(op.f('ix_booking_invoices_booking_reference'), table_name='booking_invoices')
    op.drop_table('booking_invoices')
    # ### end Alembic commands ###
