"""initial_schema

Revision ID: f7849eecf82b
Revises: 57d4103ca424
Create Date: 2026-08-02 12:56:24.128459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7849eecf82b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('llm_provider_used', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_execution_logs_agent_name'), 'agent_execution_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_id'), 'agent_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_trace_id'), 'agent_execution_logs', ['trace_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('review_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payment_gateway', sa.String(length=50), nullable=True),
    sa.Column('payment_charge_id', sa.String(length=100), nullable=True),
    sa.Column('sla_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_sla_breached', sa.Boolean(), nullable=False),
    sa.Column('timeout_behavior', sa.String(length=50), nullable=False),
    sa.Column('assigned_role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_index(op.f('ix_approval_requests_reference_id'), 'approval_requests', ['reference_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_request_type'), 'approval_requests', ['request_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('auto_approval_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.String(length=50), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_user_trust_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('requires_clean_fraud_check', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_approval_rules_id'), 'auto_approval_rules', ['id'], unique=False)
    op.create_table('booking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_events_booking_reference'), 'booking_events', ['booking_reference'], unique=False)
    op.create_index(op.f('ix_booking_events_id'), 'booking_events', ['id'], unique=False)
    op.create_table('bus_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(length=100), nullable=False),
    sa.Column('bus_type', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('departure_time', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('seats_left', sa.Integer(), nullable=False),
    sa.Column('seats_map', sa.JSON(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_routes_id'), 'bus_routes', ['id'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=True)
    op.create_table('country_visa_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_visa_requirements_country'), 'country_visa_requirements', ['country'], unique=True)
    op.create_index(op.f('ix_country_visa_requirements_id'), 'country_visa_requirements', ['id'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('min_order_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.create_table('cruise_itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cruise_line', sa.String(length=100), nullable=False),
    sa.Column('cabin_type', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('departure_port', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruise_itineraries_id'), 'cruise_itineraries', ['id'], unique=False)
    op.create_index(op.f('ix_cruise_itineraries_name'), 'cruise_itineraries', ['name'], unique=True)
    op.create_table('currency_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('rate_to_inr', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_exchanges_code'), 'currency_exchanges', ['code'], unique=True)
    op.create_index(op.f('ix_currency_exchanges_id'), 'currency_exchanges', ['id'], unique=False)
    op.create_table('destination_cost_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('daily_food_cost', sa.Integer(), nullable=False),
    sa.Column('daily_transport_cost', sa.Integer(), nullable=False),
    sa.Column('daily_activities_cost', sa.Integer(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_cost_baselines_destination'), 'destination_cost_baselines', ['destination'], unique=True)
    op.create_index(op.f('ix_destination_cost_baselines_id'), 'destination_cost_baselines', ['id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('evidence_due_by', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_booking_reference'), 'disputes', ['booking_reference'], unique=False)
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
    op.create_table('flight_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=10), nullable=False),
    sa.Column('airline_code', sa.String(length=10), nullable=False),
    sa.Column('airline_name', sa.String(length=100), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('departure_time', sa.String(length=50), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_routes_id'), 'flight_routes', ['id'], unique=False)
    op.create_table('holiday_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('inclusions', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holiday_packages_id'), 'holiday_packages', ['id'], unique=False)
    op.create_index(op.f('ix_holiday_packages_name'), 'holiday_packages', ['name'], unique=True)
    op.create_table('insurance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coverage_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plans_id'), 'insurance_plans', ['id'], unique=False)
    op.create_table('ledger_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_rows_booking_reference'), 'ledger_rows', ['booking_reference'], unique=False)
    op.create_index(op.f('ix_ledger_rows_id'), 'ledger_rows', ['id'], unique=False)
    op.create_table('llm_router_decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=False),
    sa.Column('chosen_provider', sa.String(length=50), nullable=False),
    sa.Column('cost_ceiling', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_router_decision_logs_id'), 'llm_router_decision_logs', ['id'], unique=False)
    op.create_index(op.f('ix_llm_router_decision_logs_request_type'), 'llm_router_decision_logs', ['request_type'], unique=False)
    op.create_index(op.f('ix_llm_router_decision_logs_trace_id'), 'llm_router_decision_logs', ['trace_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=150), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('blur_hash_base64', sa.Text(), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_media_owner_id'), 'media', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_owner_type'), 'media', ['owner_type'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('billing_details', sa.Text(), nullable=True),
    sa.Column('max_fare_class', sa.String(length=50), nullable=False),
    sa.Column('max_hotel_rating', sa.Integer(), nullable=False),
    sa.Column('per_diem_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('price_drop_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=100), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('checked_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_drop_claims_booking_reference'), 'price_drop_claims', ['booking_reference'], unique=False)
    op.create_index(op.f('ix_price_drop_claims_id'), 'price_drop_claims', ['id'], unique=False)
    op.create_table('settlement_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=False),
    sa.Column('batch_reference', sa.String(length=100), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_batches_batch_reference'), 'settlement_batches', ['batch_reference'], unique=True)
    op.create_index(op.f('ix_settlement_batches_id'), 'settlement_batches', ['id'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_code'), 'states', ['code'], unique=True)
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=True)
    op.create_table('toll_plazas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=150), nullable=False),
    sa.Column('toll_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toll_plazas_id'), 'toll_plazas', ['id'], unique=False)
    op.create_table('train_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=20), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=False),
    sa.Column('origin_station', sa.String(length=100), nullable=False),
    sa.Column('destination_station', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('classes_json', sa.JSON(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_routes_id'), 'train_routes', ['id'], unique=False)
    op.create_index(op.f('ix_train_routes_train_number'), 'train_routes', ['train_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('preferred_currency', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vendor_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('gross_bookings_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_deducted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_payout_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ledger_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_payouts_id'), 'vendor_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_payouts_vendor_id'), 'vendor_payouts', ['vendor_id'], unique=False)
    op.create_table('activity_bookings',
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('activity_time', sa.DateTime(), nullable=False),
    sa.Column('ticket_count', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_bookings_booking_reference'), 'activity_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_activity_bookings_id'), 'activity_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_activity_bookings_status'), 'activity_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_activity_bookings_user_id'), 'activity_bookings', ['user_id'], unique=False)
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_code'), 'airports', ['code'], unique=True)
    op.create_index(op.f('ix_airports_id'), 'airports', ['id'], unique=False)
    op.create_table('bus_bookings',
    sa.Column('operator_name', sa.String(length=100), nullable=False),
    sa.Column('bus_type', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('seat_numbers', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_bookings_booking_reference'), 'bus_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_bus_bookings_id'), 'bus_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bus_bookings_status'), 'bus_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bus_bookings_user_id'), 'bus_bookings', ['user_id'], unique=False)
    op.create_table('bus_terminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_terminals_code'), 'bus_terminals', ['code'], unique=True)
    op.create_index(op.f('ix_bus_terminals_id'), 'bus_terminals', ['id'], unique=False)
    op.create_table('cab_bookings',
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('cab_type', sa.String(length=50), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('drop_address', sa.String(length=500), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_bookings_booking_reference'), 'cab_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_cab_bookings_id'), 'cab_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_cab_bookings_status'), 'cab_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_cab_bookings_user_id'), 'cab_bookings', ['user_id'], unique=False)
    op.create_table('cab_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=150), nullable=True),
    sa.Column('driver_rating', sa.String(length=10), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_vehicles_id'), 'cab_vehicles', ['id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('messages_json', sa.JSON(), nullable=False),
    sa.Column('active_agent_context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_id'), 'conversation_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_session_id'), 'conversation_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_conversation_sessions_user_id'), 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('cruise_bookings',
    sa.Column('cruise_line', sa.String(length=100), nullable=False),
    sa.Column('ship_name', sa.String(length=100), nullable=False),
    sa.Column('departure_port', sa.String(length=100), nullable=False),
    sa.Column('arrival_port', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('cabin_number', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruise_bookings_booking_reference'), 'cruise_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_cruise_bookings_id'), 'cruise_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_cruise_bookings_status'), 'cruise_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_cruise_bookings_user_id'), 'cruise_bookings', ['user_id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_code'), 'districts', ['code'], unique=False)
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_table('employee_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_user_org')
    )
    op.create_index(op.f('ix_employee_links_id'), 'employee_links', ['id'], unique=False)
    op.create_index(op.f('ix_employee_links_org_id'), 'employee_links', ['org_id'], unique=False)
    op.create_index(op.f('ix_employee_links_user_id'), 'employee_links', ['user_id'], unique=False)
    op.create_table('flight_bookings',
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=10), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('airline_code', sa.String(length=10), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('cabin_class', sa.String(length=50), nullable=False),
    sa.Column('passenger_details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_bookings_booking_reference'), 'flight_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_flight_bookings_id'), 'flight_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_flight_bookings_status'), 'flight_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_flight_bookings_user_id'), 'flight_bookings', ['user_id'], unique=False)
    op.create_table('forex_orders',
    sa.Column('currency_pair', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_locked_at_order', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('delivery_mode', sa.String(length=50), nullable=False),
    sa.Column('kyc_ref', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_orders_booking_reference'), 'forex_orders', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_forex_orders_id'), 'forex_orders', ['id'], unique=False)
    op.create_index(op.f('ix_forex_orders_status'), 'forex_orders', ['status'], unique=False)
    op.create_index(op.f('ix_forex_orders_user_id'), 'forex_orders', ['user_id'], unique=False)
    op.create_table('holiday_package_bookings',
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('itinerary_summary', sa.String(length=2000), nullable=True),
    sa.Column('included_services', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holiday_package_bookings_booking_reference'), 'holiday_package_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_holiday_package_bookings_id'), 'holiday_package_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_holiday_package_bookings_status'), 'holiday_package_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_holiday_package_bookings_user_id'), 'holiday_package_bookings', ['user_id'], unique=False)
    op.create_table('hotel_bookings',
    sa.Column('hotel_name', sa.String(length=255), nullable=False),
    sa.Column('hotel_id', sa.String(length=100), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('guest_details', sa.JSON(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_bookings_booking_reference'), 'hotel_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_hotel_bookings_id'), 'hotel_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_hotel_bookings_status'), 'hotel_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_hotel_bookings_user_id'), 'hotel_bookings', ['user_id'], unique=False)
    op.create_table('hotel_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('star_rating', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities_json', sa.JSON(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_properties_id'), 'hotel_properties', ['id'], unique=False)
    op.create_index(op.f('ix_hotel_properties_name'), 'hotel_properties', ['name'], unique=True)
    op.create_table('insurance_policies',
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('coverage_details', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policies_booking_reference'), 'insurance_policies', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_insurance_policies_id'), 'insurance_policies', ['id'], unique=False)
    op.create_index(op.f('ix_insurance_policies_policy_number'), 'insurance_policies', ['policy_number'], unique=True)
    op.create_index(op.f('ix_insurance_policies_status'), 'insurance_policies', ['status'], unique=False)
    op.create_index(op.f('ix_insurance_policies_user_id'), 'insurance_policies', ['user_id'], unique=False)
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_loyalty_accounts_id'), 'loyalty_accounts', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_attempts_booking_reference'), 'payment_attempts', ['booking_reference'], unique=False)
    op.create_index(op.f('ix_payment_attempts_id'), 'payment_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_user_id'), 'payment_attempts', ['user_id'], unique=False)
    op.create_table('reconciliation_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('exception_type', sa.String(length=50), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['settlement_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_exceptions_booking_reference'), 'reconciliation_exceptions', ['booking_reference'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_id'), 'reconciliation_exceptions', ['id'], unique=False)
    op.create_table('saved_payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=False),
    sa.Column('payment_token', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_payment_methods_id'), 'saved_payment_methods', ['id'], unique=False)
    op.create_index(op.f('ix_saved_payment_methods_user_id'), 'saved_payment_methods', ['user_id'], unique=False)
    op.create_table('saved_travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linked_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('passport_no', sa.String(length=50), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_travelers_id'), 'saved_travelers', ['id'], unique=False)
    op.create_index(op.f('ix_saved_travelers_linked_user_id'), 'saved_travelers', ['linked_user_id'], unique=False)
    op.create_table('tour_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_activities_id'), 'tour_activities', ['id'], unique=False)
    op.create_index(op.f('ix_tour_activities_name'), 'tour_activities', ['name'], unique=True)
    op.create_table('train_bookings',
    sa.Column('train_number', sa.String(length=20), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=False),
    sa.Column('origin_station', sa.String(length=100), nullable=False),
    sa.Column('destination_station', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('coach_class', sa.String(length=20), nullable=False),
    sa.Column('passenger_details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_bookings_booking_reference'), 'train_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_train_bookings_id'), 'train_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_train_bookings_status'), 'train_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_train_bookings_user_id'), 'train_bookings', ['user_id'], unique=False)
    op.create_table('train_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_stations_code'), 'train_stations', ['code'], unique=True)
    op.create_index(op.f('ix_train_stations_id'), 'train_stations', ['id'], unique=False)
    op.create_table('user_preference_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chromadb_collection', sa.String(length=100), nullable=False),
    sa.Column('chromadb_doc_id', sa.String(length=100), nullable=False),
    sa.Column('preference_category', sa.String(length=50), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preference_embeddings_chromadb_doc_id'), 'user_preference_embeddings', ['chromadb_doc_id'], unique=True)
    op.create_index(op.f('ix_user_preference_embeddings_id'), 'user_preference_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_user_preference_embeddings_user_id'), 'user_preference_embeddings', ['user_id'], unique=False)
    op.create_table('vehicle_rental_bookings',
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('drop_time', sa.DateTime(), nullable=False),
    sa.Column('vehicle_name', sa.String(length=255), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('self_drive', sa.Boolean(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('kyc_ref', sa.String(length=100), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('qr_handover_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_rental_bookings_booking_reference'), 'vehicle_rental_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_vehicle_rental_bookings_id'), 'vehicle_rental_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_rental_bookings_status'), 'vehicle_rental_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_rental_bookings_user_id'), 'vehicle_rental_bookings', ['user_id'], unique=False)
    op.create_table('villa_bookings',
    sa.Column('villa_name', sa.String(length=255), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.String(length=100), nullable=False),
    sa.Column('house_rules', sa.String(length=1000), nullable=True),
    sa.Column('amenities_json', sa.JSON(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villa_bookings_booking_reference'), 'villa_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_villa_bookings_id'), 'villa_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_villa_bookings_status'), 'villa_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_villa_bookings_user_id'), 'villa_bookings', ['user_id'], unique=False)
    op.create_table('villa_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=False),
    sa.Column('host_name', sa.String(length=150), nullable=False),
    sa.Column('house_rules', sa.Text(), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villa_properties_id'), 'villa_properties', ['id'], unique=False)
    op.create_index(op.f('ix_villa_properties_name'), 'villa_properties', ['name'], unique=True)
    op.create_table('visa_applications',
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('visa_type', sa.String(length=50), nullable=False),
    sa.Column('applicant_details', sa.JSON(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('status_notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_APPROVAL', 'PENDING_ADMIN_APPROVAL', 'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', 'REFUND_INITIATED', 'REFUNDED', 'REJECTED', 'CANCELLATION_REQUEST_SENT', 'REFUND_REQUEST_SENT', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'VEHICLE_HANDED_OVER', 'TRIP_ACTIVE', 'RETURNED', 'OFFER_SELECTED', 'AWAITING_HUMAN_PAYMENT_APPROVAL', 'PAYMENT_PROCESSING', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('cancellation_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('linked_booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_applications_booking_reference'), 'visa_applications', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_visa_applications_id'), 'visa_applications', ['id'], unique=False)
    op.create_index(op.f('ix_visa_applications_status'), 'visa_applications', ['status'], unique=False)
    op.create_index(op.f('ix_visa_applications_user_id'), 'visa_applications', ['user_id'], unique=False)
    op.create_table('wallet_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_wallet_accounts_id'), 'wallet_accounts', ['id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_ref_id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlist_items_id'), 'wishlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_item_ref_id'), 'wishlist_items', ['item_ref_id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_item_type'), 'wishlist_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_wishlist_items_user_id'), 'wishlist_items', ['user_id'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_ref_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    op.create_index(op.f('ix_wishlists_user_id'), 'wishlists', ['user_id'], unique=False)
    op.create_table('hotel_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_rooms_id'), 'hotel_rooms', ['id'], unique=False)
    op.create_table('localities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('population_tier', sa.Integer(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('has_rental_hub', sa.Boolean(), nullable=False),
    sa.Column('nearest_hub_locality_id', sa.Integer(), nullable=True),
    sa.Column('delivery_radius_km', sa.Float(), nullable=False),
    sa.Column('delivery_fee_beyond_radius', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['nearest_hub_locality_id'], ['localities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localities_id'), 'localities', ['id'], unique=False)
    op.create_index(op.f('ix_localities_name'), 'localities', ['name'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loyalty_account_id', sa.Integer(), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('booking_ref', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loyalty_account_id'], ['loyalty_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_transactions_id'), 'loyalty_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_loyalty_account_id'), 'loyalty_transactions', ['loyalty_account_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['wallet_account_id'], ['wallet_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_account_id'), 'wallet_transactions', ['wallet_account_id'], unique=False)
    op.create_table('rental_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('hub_locality_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('transmission', sa.String(length=50), nullable=False),
    sa.Column('seating_capacity', sa.Integer(), nullable=False),
    sa.Column('self_drive_available', sa.Boolean(), nullable=False),
    sa.Column('with_driver_available', sa.Boolean(), nullable=False),
    sa.Column('rental_mode', sa.String(length=50), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('instant_confirm', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['hub_locality_id'], ['localities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_vehicles_id'), 'rental_vehicles', ['id'], unique=False)
    op.create_table('vehicle_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['rental_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_availabilities_end_date'), 'vehicle_availabilities', ['end_date'], unique=False)
    op.create_index(op.f('ix_vehicle_availabilities_id'), 'vehicle_availabilities', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_availabilities_start_date'), 'vehicle_availabilities', ['start_date'], unique=False)
    op.create_index(op.f('ix_vehicle_availabilities_vehicle_id'), 'vehicle_availabilities', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_availabilities_vehicle_id'), table_name='vehicle_availabilities')
    op.drop_index(op.f('ix_vehicle_availabilities_start_date'), table_name='vehicle_availabilities')
    op.drop_index(op.f('ix_vehicle_availabilities_id'), table_name='vehicle_availabilities')
    op.drop_index(op.f('ix_vehicle_availabilities_end_date'), table_name='vehicle_availabilities')
    op.drop_table('vehicle_availabilities')
    op.drop_index(op.f('ix_rental_vehicles_id'), table_name='rental_vehicles')
    op.drop_table('rental_vehicles')
    op.drop_index(op.f('ix_wallet_transactions_wallet_account_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_loyalty_account_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_id'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index(op.f('ix_localities_name'), table_name='localities')
    op.drop_index(op.f('ix_localities_id'), table_name='localities')
    op.drop_table('localities')
    op.drop_index(op.f('ix_hotel_rooms_id'), table_name='hotel_rooms')
    op.drop_table('hotel_rooms')
    op.drop_index(op.f('ix_wishlists_user_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_wishlist_items_user_id'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_item_type'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_item_ref_id'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_id'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('ix_wallet_accounts_id'), table_name='wallet_accounts')
    op.drop_table('wallet_accounts')
    op.drop_index(op.f('ix_visa_applications_user_id'), table_name='visa_applications')
    op.drop_index(op.f('ix_visa_applications_status'), table_name='visa_applications')
    op.drop_index(op.f('ix_visa_applications_id'), table_name='visa_applications')
    op.drop_index(op.f('ix_visa_applications_booking_reference'), table_name='visa_applications')
    op.drop_table('visa_applications')
    op.drop_index(op.f('ix_villa_properties_name'), table_name='villa_properties')
    op.drop_index(op.f('ix_villa_properties_id'), table_name='villa_properties')
    op.drop_table('villa_properties')
    op.drop_index(op.f('ix_villa_bookings_user_id'), table_name='villa_bookings')
    op.drop_index(op.f('ix_villa_bookings_status'), table_name='villa_bookings')
    op.drop_index(op.f('ix_villa_bookings_id'), table_name='villa_bookings')
    op.drop_index(op.f('ix_villa_bookings_booking_reference'), table_name='villa_bookings')
    op.drop_table('villa_bookings')
    op.drop_index(op.f('ix_vehicle_rental_bookings_user_id'), table_name='vehicle_rental_bookings')
    op.drop_index(op.f('ix_vehicle_rental_bookings_status'), table_name='vehicle_rental_bookings')
    op.drop_index(op.f('ix_vehicle_rental_bookings_id'), table_name='vehicle_rental_bookings')
    op.drop_index(op.f('ix_vehicle_rental_bookings_booking_reference'), table_name='vehicle_rental_bookings')
    op.drop_table('vehicle_rental_bookings')
    op.drop_index(op.f('ix_user_preference_embeddings_user_id'), table_name='user_preference_embeddings')
    op.drop_index(op.f('ix_user_preference_embeddings_id'), table_name='user_preference_embeddings')
    op.drop_index(op.f('ix_user_preference_embeddings_chromadb_doc_id'), table_name='user_preference_embeddings')
    op.drop_table('user_preference_embeddings')
    op.drop_index(op.f('ix_train_stations_id'), table_name='train_stations')
    op.drop_index(op.f('ix_train_stations_code'), table_name='train_stations')
    op.drop_table('train_stations')
    op.drop_index(op.f('ix_train_bookings_user_id'), table_name='train_bookings')
    op.drop_index(op.f('ix_train_bookings_status'), table_name='train_bookings')
    op.drop_index(op.f('ix_train_bookings_id'), table_name='train_bookings')
    op.drop_index(op.f('ix_train_bookings_booking_reference'), table_name='train_bookings')
    op.drop_table('train_bookings')
    op.drop_index(op.f('ix_tour_activities_name'), table_name='tour_activities')
    op.drop_index(op.f('ix_tour_activities_id'), table_name='tour_activities')
    op.drop_table('tour_activities')
    op.drop_index(op.f('ix_saved_travelers_linked_user_id'), table_name='saved_travelers')
    op.drop_index(op.f('ix_saved_travelers_id'), table_name='saved_travelers')
    op.drop_table('saved_travelers')
    op.drop_index(op.f('ix_saved_payment_methods_user_id'), table_name='saved_payment_methods')
    op.drop_index(op.f('ix_saved_payment_methods_id'), table_name='saved_payment_methods')
    op.drop_table('saved_payment_methods')
    op.drop_index(op.f('ix_reconciliation_exceptions_id'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_booking_reference'), table_name='reconciliation_exceptions')
    op.drop_table('reconciliation_exceptions')
    op.drop_index(op.f('ix_payment_attempts_user_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_booking_reference'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_loyalty_accounts_id'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    op.drop_index(op.f('ix_insurance_policies_user_id'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_status'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_policy_number'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_id'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_booking_reference'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_index(op.f('ix_hotel_properties_name'), table_name='hotel_properties')
    op.drop_index(op.f('ix_hotel_properties_id'), table_name='hotel_properties')
    op.drop_table('hotel_properties')
    op.drop_index(op.f('ix_hotel_bookings_user_id'), table_name='hotel_bookings')
    op.drop_index(op.f('ix_hotel_bookings_status'), table_name='hotel_bookings')
    op.drop_index(op.f('ix_hotel_bookings_id'), table_name='hotel_bookings')
    op.drop_index(op.f('ix_hotel_bookings_booking_reference'), table_name='hotel_bookings')
    op.drop_table('hotel_bookings')
    op.drop_index(op.f('ix_holiday_package_bookings_user_id'), table_name='holiday_package_bookings')
    op.drop_index(op.f('ix_holiday_package_bookings_status'), table_name='holiday_package_bookings')
    op.drop_index(op.f('ix_holiday_package_bookings_id'), table_name='holiday_package_bookings')
    op.drop_index(op.f('ix_holiday_package_bookings_booking_reference'), table_name='holiday_package_bookings')
    op.drop_table('holiday_package_bookings')
    op.drop_index(op.f('ix_forex_orders_user_id'), table_name='forex_orders')
    op.drop_index(op.f('ix_forex_orders_status'), table_name='forex_orders')
    op.drop_index(op.f('ix_forex_orders_id'), table_name='forex_orders')
    op.drop_index(op.f('ix_forex_orders_booking_reference'), table_name='forex_orders')
    op.drop_table('forex_orders')
    op.drop_index(op.f('ix_flight_bookings_user_id'), table_name='flight_bookings')
    op.drop_index(op.f('ix_flight_bookings_status'), table_name='flight_bookings')
    op.drop_index(op.f('ix_flight_bookings_id'), table_name='flight_bookings')
    op.drop_index(op.f('ix_flight_bookings_booking_reference'), table_name='flight_bookings')
    op.drop_table('flight_bookings')
    op.drop_index(op.f('ix_employee_links_user_id'), table_name='employee_links')
    op.drop_index(op.f('ix_employee_links_org_id'), table_name='employee_links')
    op.drop_index(op.f('ix_employee_links_id'), table_name='employee_links')
    op.drop_table('employee_links')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_cruise_bookings_user_id'), table_name='cruise_bookings')
    op.drop_index(op.f('ix_cruise_bookings_status'), table_name='cruise_bookings')
    op.drop_index(op.f('ix_cruise_bookings_id'), table_name='cruise_bookings')
    op.drop_index(op.f('ix_cruise_bookings_booking_reference'), table_name='cruise_bookings')
    op.drop_table('cruise_bookings')
    op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_session_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_cab_vehicles_id'), table_name='cab_vehicles')
    op.drop_table('cab_vehicles')
    op.drop_index(op.f('ix_cab_bookings_user_id'), table_name='cab_bookings')
    op.drop_index(op.f('ix_cab_bookings_status'), table_name='cab_bookings')
    op.drop_index(op.f('ix_cab_bookings_id'), table_name='cab_bookings')
    op.drop_index(op.f('ix_cab_bookings_booking_reference'), table_name='cab_bookings')
    op.drop_table('cab_bookings')
    op.drop_index(op.f('ix_bus_terminals_id'), table_name='bus_terminals')
    op.drop_index(op.f('ix_bus_terminals_code'), table_name='bus_terminals')
    op.drop_table('bus_terminals')
    op.drop_index(op.f('ix_bus_bookings_user_id'), table_name='bus_bookings')
    op.drop_index(op.f('ix_bus_bookings_status'), table_name='bus_bookings')
    op.drop_index(op.f('ix_bus_bookings_id'), table_name='bus_bookings')
    op.drop_index(op.f('ix_bus_bookings_booking_reference'), table_name='bus_bookings')
    op.drop_table('bus_bookings')
    op.drop_index(op.f('ix_airports_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_code'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_activity_bookings_user_id'), table_name='activity_bookings')
    op.drop_index(op.f('ix_activity_bookings_status'), table_name='activity_bookings')
    op.drop_index(op.f('ix_activity_bookings_id'), table_name='activity_bookings')
    op.drop_index(op.f('ix_activity_bookings_booking_reference'), table_name='activity_bookings')
    op.drop_table('activity_bookings')
    op.drop_index(op.f('ix_vendor_payouts_vendor_id'), table_name='vendor_payouts')
    op.drop_index(op.f('ix_vendor_payouts_id'), table_name='vendor_payouts')
    op.drop_table('vendor_payouts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_train_routes_train_number'), table_name='train_routes')
    op.drop_index(op.f('ix_train_routes_id'), table_name='train_routes')
    op.drop_table('train_routes')
    op.drop_index(op.f('ix_toll_plazas_id'), table_name='toll_plazas')
    op.drop_table('toll_plazas')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.drop_index(op.f('ix_states_code'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_settlement_batches_id'), table_name='settlement_batches')
    op.drop_index(op.f('ix_settlement_batches_batch_reference'), table_name='settlement_batches')
    op.drop_table('settlement_batches')
    op.drop_index(op.f('ix_price_drop_claims_id'), table_name='price_drop_claims')
    op.drop_index(op.f('ix_price_drop_claims_booking_reference'), table_name='price_drop_claims')
    op.drop_table('price_drop_claims')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_media_owner_type'), table_name='media')
    op.drop_index(op.f('ix_media_owner_id'), table_name='media')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_llm_router_decision_logs_trace_id'), table_name='llm_router_decision_logs')
    op.drop_index(op.f('ix_llm_router_decision_logs_request_type'), table_name='llm_router_decision_logs')
    op.drop_index(op.f('ix_llm_router_decision_logs_id'), table_name='llm_router_decision_logs')
    op.drop_table('llm_router_decision_logs')
    op.drop_index(op.f('ix_ledger_rows_id'), table_name='ledger_rows')
    op.drop_index(op.f('ix_ledger_rows_booking_reference'), table_name='ledger_rows')
    op.drop_table('ledger_rows')
    op.drop_index(op.f('ix_insurance_plans_id'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    op.drop_index(op.f('ix_holiday_packages_name'), table_name='holiday_packages')
    op.drop_index(op.f('ix_holiday_packages_id'), table_name='holiday_packages')
    op.drop_table('holiday_packages')
    op.drop_index(op.f('ix_flight_routes_id'), table_name='flight_routes')
    op.drop_table('flight_routes')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_booking_reference'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_destination_cost_baselines_id'), table_name='destination_cost_baselines')
    op.drop_index(op.f('ix_destination_cost_baselines_destination'), table_name='destination_cost_baselines')
    op.drop_table('destination_cost_baselines')
    op.drop_index(op.f('ix_currency_exchanges_id'), table_name='currency_exchanges')
    op.drop_index(op.f('ix_currency_exchanges_code'), table_name='currency_exchanges')
    op.drop_table('currency_exchanges')
    op.drop_index(op.f('ix_cruise_itineraries_name'), table_name='cruise_itineraries')
    op.drop_index(op.f('ix_cruise_itineraries_id'), table_name='cruise_itineraries')
    op.drop_table('cruise_itineraries')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_country_visa_requirements_id'), table_name='country_visa_requirements')
    op.drop_index(op.f('ix_country_visa_requirements_country'), table_name='country_visa_requirements')
    op.drop_table('country_visa_requirements')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_bus_routes_id'), table_name='bus_routes')
    op.drop_table('bus_routes')
    op.drop_index(op.f('ix_booking_events_id'), table_name='booking_events')
    op.drop_index(op.f('ix_booking_events_booking_reference'), table_name='booking_events')
    op.drop_table('booking_events')
    op.drop_index(op.f('ix_auto_approval_rules_id'), table_name='auto_approval_rules')
    op.drop_table('auto_approval_rules')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approval_requests_request_type'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_reference_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_agent_execution_logs_trace_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_agent_name'), table_name='agent_execution_logs')
    op.drop_table('agent_execution_logs')
    # ### end Alembic commands ###
