"""add_showcase_tables

Revision ID: fdae31d52a80
Revises: 57d4103ca424
Create Date: 2026-08-02 13:41:46.397783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdae31d52a80'
down_revision = '57d4103ca424'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('brand_gradient', sa.String(length=100), nullable=True),
    sa.Column('deep_link', sa.String(length=255), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airline_partners_id'), 'airline_partners', ['id'], unique=False)
    op.create_index(op.f('ix_airline_partners_name'), 'airline_partners', ['name'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('collection_type', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index(op.f('ix_collections_slug'), 'collections', ['slug'], unique=True)
    op.create_table('footer_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_footer_sections_id'), 'footer_sections', ['id'], unique=False)
    op.create_table('hotel_brand_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('property_image_url', sa.String(length=255), nullable=True),
    sa.Column('deep_link', sa.String(length=255), nullable=True),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_brand_partners_id'), 'hotel_brand_partners', ['id'], unique=False)
    op.create_index(op.f('ix_hotel_brand_partners_name'), 'hotel_brand_partners', ['name'], unique=True)
    op.create_table('info_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('cta_url', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_highlights_id'), 'info_highlights', ['id'], unique=False)
    op.create_table('promo_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('background_color', sa.String(length=100), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('cta_text', sa.String(length=100), nullable=False),
    sa.Column('cta_url', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('placement', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_banners_id'), 'promo_banners', ['id'], unique=False)
    op.create_index(op.f('ix_promo_banners_placement'), 'promo_banners', ['placement'], unique=False)
    op.create_table('promotional_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('promo_code', sa.String(length=30), nullable=True),
    sa.Column('cta_url', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotional_offers_category'), 'promotional_offers', ['category'], unique=False)
    op.create_index(op.f('ix_promotional_offers_id'), 'promotional_offers', ['id'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=False),
    sa.Column('custom_image_url', sa.String(length=555), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('tag_text', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_items_id'), 'collection_items', ['id'], unique=False)
    op.create_table('footer_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['footer_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_footer_links_id'), 'footer_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_footer_links_id'), table_name='footer_links')
    op.drop_table('footer_links')
    op.drop_index(op.f('ix_collection_items_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_promotional_offers_id'), table_name='promotional_offers')
    op.drop_index(op.f('ix_promotional_offers_category'), table_name='promotional_offers')
    op.drop_table('promotional_offers')
    op.drop_index(op.f('ix_promo_banners_placement'), table_name='promo_banners')
    op.drop_index(op.f('ix_promo_banners_id'), table_name='promo_banners')
    op.drop_table('promo_banners')
    op.drop_index(op.f('ix_info_highlights_id'), table_name='info_highlights')
    op.drop_table('info_highlights')
    op.drop_index(op.f('ix_hotel_brand_partners_name'), table_name='hotel_brand_partners')
    op.drop_index(op.f('ix_hotel_brand_partners_id'), table_name='hotel_brand_partners')
    op.drop_table('hotel_brand_partners')
    op.drop_index(op.f('ix_footer_sections_id'), table_name='footer_sections')
    op.drop_table('footer_sections')
    op.drop_index(op.f('ix_collections_slug'), table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_airline_partners_name'), table_name='airline_partners')
    op.drop_index(op.f('ix_airline_partners_id'), table_name='airline_partners')
    op.drop_table('airline_partners')
    # ### end Alembic commands ###
